---
project_identifier: codeorg
api_key: 4b885c35a689841979bf23003320e936
base_path: locales

files:
  -
    source: '/en-US/**/*.yml'
    translation: '/%locale%/**/%original_file_name%'
  -
    source: '/en-US/**/*.json'
    translation: '/%locale%/**/%original_file_name%'
